# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, development-build ]
  pull_request:
    branches: [ master, development-build ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get install xvfb
    - run: npm ci
    - name: Start testing
      env:
        CI: true
#     run: |
#       xvfb-run --auto-servernum npm run test:e2e
#       xvfb-run --auto-servernum npm run test:unit
#       grunt
      run: |
        grunt        
    - name: Cleanup artifacts
      run: |
        npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
        npm run release
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ubuntu-latest-artifact
        path: dist
    #- name: Release
    #  uses: softprops/action-gh-release@v1
    #  if: startsWith(github.ref, 'refs/tags/')
    #  with:
    #    files: "dist/**"
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
